[package]
name = "cargo-exam"
version = "0.1.0"
edition = "2021"
description = "cargo sub-command cause I can't remeber test commands"
license = "MIT"

[dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
